import Nav from "@/components/Home/Navbar";
import "../../styles/globals.css";
import { Toaster } from "sonner";

export const metadata = {
  title: "Daily Bloom",
  description: "Generated by Group One",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body>
        <Nav />
        <main>
          <Toaster />
          {children}
        </main>
      </body>
    </html>
  );
}
