import Navbar from "@/components/Dashboard_Home/Navbar";
import Sidebar from "@/components/Dashboard_Home/Sidebar";
import "../../styles/globals.css";

export const metadata = {
  title: "Daily Bloom",
  description: "Generated by Group One",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body>
        <main className="flex w-[100vw] h-[100vh] overflow-hidden">
          <Sidebar />

          <div className="relative w-full h-[100vh] bg-backgroundSecondary">
            <Navbar />
            <div className="w-full h-full overflow-y-auto pt-[130px] pb-[80px]">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
