import "../styles/globals.css";
import { SessionProvider } from "../components/Habits_Management/SessionProvider";

export const metadata = {
  title: "Daily Bloom",
  description: "Generated by Group One",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
